### PR TITLE
elegu and water layer name changed, added scroll to sidebar

### PR DESCRIPTION
**Pull request by lynnnakiganda**

### CODE REVIEW

**Comment by RonKbS** [comment]
Hi @lynnnakiganda ,

The change you made to add the scroll bar breaks the sidebar as shown below.
Please look into it
Annotation 2020-06-11 085158

**Comment by RonKbS** [comment]
The previous one looks as below
Annotation 2020-06-11 085500

**Comment by lynnnakiganda** [comment]
Hey @RonKbS how is it broken exactly because all am seeing a visible scroll bar as the difference in the pictures

**Comment by RonKbS** [comment]
> Hey @RonKbS how is it broken exactly because all am seeing a visible scroll bar as the difference in the pictures

The logos are scrolling up as well, @lynnnakiganda .

**Comment by lynnnakiganda** [comment]
Okay I'll make sure the logos don't move and push again

**Pull request merged**
